export const ADD_TASK = "ADD_TASK";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAILURE = "ADD_TASK_FAILURE";

export const GET_TASKS = "GET_TASK";
export const GET_TASKS_SUCCESS = "GET_TASK_SUCCESS";
export const GET_TASKS_FAILURE = "GET_TASKS_FAILURE";
